packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@turbo/gen": 1.12.4
  eslint: 9.16.0
  next: 15.0.3
  prettier: 3.4.1
  turbo: 2.3.3
  typescript: 5.5.4
  "@types/node": 20.11.24
  lint-staged: 15.2.10
  "@changesets/cli": "2.27.10"
  husky: 9.1.7
catalogs:
  react19:
    react: 19.0.0-rc-66855b96-20241106
    react-dom: 19.0.0-rc-66855b96-20241106
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": 18.3.1
    "@types/react-dom": 18.3.1
  next15:
    next: 15.0.3
  "@commitlint":
    "@commitlint/cli": 19.6.0
    "@commitlint/config-conventional": 19.6.0
